Add Nexii to list of blacklisted devices, add secondary option for theme only disabling
Magisk-Modules-Repo/Pix3lify pull request #41
Opened 2018-12-31 23:46 UTC by lazerl0rd

Thx to @ThatNerdyPikachu

2018-12-31 23:51 UTC, ThatNerdyPikachu commented
Is that okay if I move some other changes from my additions to yours?

2018-12-31 23:51 UTC, lazerl0rd commented
> 
> 
> Is that okay if I move some other changes from my additions to yours?

Such as?

2018-12-31 23:52 UTC, ThatNerdyPikachu commented
Some of the wording + the Unity downgrade. (cc @Stallix)

2018-12-31 23:55 UTC, lazerl0rd commented
> 
> 
> Some of the wording + the Unity downgrade. (cc @Stallix)

I'd check up with @JohnFawkes about the Unity downgrade. But I already incleded your grammar fixy stuff.

2018-12-31 23:57 UTC, ThatNerdyPikachu commented
@lazerl0rd Please review my changes, I'll check with John and Zack about the downgrade.

2018-12-31 23:58 UTC, lazerl0rd commented
@ThatNerdyPikachu the user needs to understand the difference between theme removal and overlay removal.

2019-01-01 00:02 UTC, ThatNerdyPikachu commented
will fix.

2019-01-01 00:22 UTC, lzlrd commented
@ThatNerdyPikachu The overlay file (Pix3lify.apk) contains more features than rounded corners. It contains Night Light too, for example.

The Pixel folder in $INSTALLER/system/vendor/overlay contains the Pixel theme. The build.prop for it you know already.

So your wording needed a bit of change ;).

2019-01-01 00:26 UTC, ThatNerdyPikachu requested changes
You broke it lol

2019-01-01 00:26 UTC, ThatNerdyPikachu commented on common/install.sh
> +    ui_print "   Enabling overlays and Pixel blue accent..."
This is supposed to disable it.

```
User wants overlay and tint?
-> Do that
Else?
-> Show a menu
    - Do they want just the overlay features?
        - Disable tint but keep overlays
    - Do they want nothing?
        - Disable everything
```

Once you fix that, I'll make my final grammar changes, as usual. (i'm too tired to fix)

2019-01-01 00:27 UTC, lzlrd commented on common/install.sh
> +    ui_print "   Enabling overlays and Pixel blue accent..."
Ahh, I see.

2019-01-01 00:29 UTC, ThatNerdyPikachu commented
Also, I cannot push to your repo, therefore I cannot upload Unity v2.2.

Can you add this in ``common``?
https://github.com/Zackptg5/Unity/blob/master/common/unityfiles.tar.gz

2019-01-01 00:40 UTC, merged